runtime: nodejs18
service: default

env_variables:
  NODE_ENV: production

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
    secure: always
